CREATE_CLIENT_TABLE = '''
    CREATE TABLE IF NOT EXISTS
    CLIENT (ID INTEGER PRIMARY KEY AUTOINCREMENT,
                USERNAME TEXT,
                PASSWORD TEXT,
                BALANCE REAL DEFAULT 0,
                MESSAGE TEXT,
                EMAIL TEXT)
'''

CREATE_BANNED_CLIENT_TABLE = '''
    CREATE TABLE IF NOT EXISTS
    BANNED_CLIENT (ID INTEGER PRIMARY KEY AUTOINCREMENT,
                    USERNAME STRING,
                    BAN_TIME REAL)
'''

BAN_CLIENT = '''
    INSERT INTO BANNED_CLIENT (USERNAME, BAN_TIME) VALUES (?, ?)
'''

REMOVE_BAN = '''
    DELETE
    FROM BANNED_CLIENT
    WHERE USERNAME = ?
'''

CHECK_FOR_BAN = '''
    SELECT *
    FROM BANNED_CLIENT
    WHERE USERNAME = ?
'''

UPDATE_CLIENT_MESSAGE = '''
    UPDATE CLIENT
    SET MESSAGE = ? WHERE id = ?
'''

UPDATE_CLIENT_PASSWORD = '''
    UPDATE CLIENT
    SET PASSWORD = ? WHERE id = ?
'''

REGISTER_CLIENT = '''
    INSERT INTO CLIENT (USERNAME, PASSWORD) VALUES (?, ?)
'''

SELECT_CLIENT = '''
    SELECT ID, USERNAME, BALANCE, MESSAGE
    FROM CLIENT WHERE USERNAME = ? AND PASSWORD = ? LIMIT 1
'''

COUNT_USER = '''SELECT Count(*)
                FROM CLIENT
                WHERE USERNAME = ? AND PASSWORD = ?
'''
