INSERT_INTO_USER = '''
    INSERT INTO USER (USERNAME, PASSWORD) VALUES (?, ?)
'''

INSERT_INTO_PROJECTION = '''
    INSERT INTO PROJECTION (MOVIE_ID, TYPE, DATE, TIME)
    VALUES (?, ?, ?, ?)
'''

INSERT_INTO_MOVIE = '''
    INSERT INTO MOVIE (NAME, RATING)
    VALUES (?, ?)
'''

INSERT_INTO_RESERVATION = '''
    INSERT INTO RESERVATION (USER_ID, PROJECTION_ID, ROW, COL)
    VALUES (?, ?, ?, ?)
'''
