CREATE_HOSPITAL_STAY = """
    CREATE TABLE IF NOT EXISTS HOSPITAL_STAY (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        ROOM INT NOT NULL,
        STARTDATE DATE NOT NULL,
        ENDDATE DATE int,
        INJURY VARCHAR(255) NOT NULL,
        PATIENT INT,
        FOREIGN KEY(PATIENT) REFERENCES PATIENTS(ID)
    )
    """

CREATE_PATIENTS_TABLE = """
    CREATE TABLE IF NOT EXISTS PATIENTS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        FIRSTNAME TEXT NOT NULL,
        LASTNAME TEXT NOT NULL,
        AGE INTEGER NOT NULL,
        GENDER VARCHAR(6),
        DOCTOR INT,
        FOREIGN KEY(DOCTOR) REFERENCES DOCTOR(ID)
    )
    """

CREATE_DOCTORS_TABLE = """
    CREATE TABLE IF NOT EXISTS DOCTORS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        FIRSTNAME VARCHAR(255) NOT NULL,
        LASTNAME VARCHAR(255) NOT NULL
    )
    """

DROP_DB = """
    DROP TABLE IF EXISTS PATIENTS;
    DROP TABLE IF EXISTS HOSPITAL_STAY;
    DROP TABLE IF EXISTS DOCTORS;
    """


SELECT_ALL_PATIENTS_OF_A_DOCTOR = """
    SELECT P.ID, P.FIRSTNAME, P.LASTNAME, P.AGE
    FROM PATIENTS AS P
    JOIN DOCTORS
    ON P.DOCTOR = DOCTORS.ID
    AND P.DOCTOR = ?"""

SELECT_PATIENTS_BY_INJURY = """
    SELECT GROUP_CONCAT(P.FIRSTNAME || " " || P.LASTNAME) AS p
    FROM PATIENTS AS P
    JOIN HOSPITAL_STAY AS H
    ON P.ID = H.PATIENT
    GROUP BY INJURY
    HAVING INJURY = ?;
    """

SELECT_DOCTORS_BY_INJURY = """
    SELECT H.INJURY , GROUP_CONCAT(D.FIRSTNAME || " " || D.LASTNAME) AS DOCTOR
    FROM HOSPITAL_STAY AS H
    JOIN PATIENTS AS P
    ON P.ID = H.PATIENT
    JOIN DOCTORS AS D
    ON P.DOCTOR = D.ID
    GROUP BY H.INJURY;"""

SELECT_PATIENTS_FROM_TO = """
    SELECT P.ID, P.FIRSTNAME, P.LASTNAME, P.AGE
    FROM PATIENTS AS P
    JOIN HOSPITAL_STAY AS H
    ON P.ID = H.PATIENT
    WHERE H.STARTDATE >= ?
    AND H.STARTDATE <= ?"""

UPDATE_DOCTOR_INFO = """UPDATE DOCTORS SET {} = ?
                         WHERE FIRSTNAME = ?"""

DELETE_DOCTOR = """
    DELETE FROM DOCTORS WHERE DOCTORS.FIRSTNAME = ?"""

INSERT_INTO_DOCTORS = """
    INSERT INTO DOCTORS (FIRSTNAME, LASTNAME) VALUES (?, ?)"""

INSERT_A_DOCTOR = "INSERT INTO DOCTORS (FIRSTNAME, LASTNAME) VALUES(?, ?)"

INSERT_INTO_HOSPITAL_STAY = """
    INSERT INTO HOSPITAL_STAY (ROOM, STARTDATE, ENDDATE, INJURY, PATIENT)
    VALUES (?, ?, ?, ?, ?);
    """

INSERT_INTO_PATIENTS = """
    INSERT INTO PATIENTS (FIRSTNAME, LASTNAME, AGE, GENDER, DOCTOR)
    VALUES(?, ?, ?, ?, ?)
    """

INSERT_A_PATIENT = """
    INSERT INTO PATIENTS (FIRSTNAME, LASTNAME, AGE)
    VALUES(?, ?, ?)"""

DELETE_PATIENT = """
    DELETE FROM PATIENTS WHERE FIRSTNAME = ?"""

UPDATE_HOSPITAL_STAY = """UPDATE HOSPITAL_STAY SET {} = ?
                          WHERE PATIENT = ?"""

UPDATE_PATIENT_INFO = """UPDATE PATIENTS SET {} = ?
                         WHERE FIRSTNAME = ?"""

DELETE_HOSPITAL_STAY = """
    DELETE FROM HOSPITAL_STAY WHERE PATIENT = ?"""

SELECT_ALL_DOCTORS = """
    SELECT ID, FIRSTNAME, LASTNAME FROM DOCTORS"""

SELECT_DOCTOR = """
    SELECT * FROM DOCTORS WHERE FIRSTNAME = ?"""

SELECT_ALL_PATIENTS = """
    SELECT ID, FIRSTNAME, LASTNAME, AGE FROM PATIENTS"""

SELECT_PATIENT = """
    SELECT * FROM PATIENTS WHERE FIRSTNAME = ?"""
